pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "chandan709/my-webapp"
        DOCKER_TAG = "latest"
    }
    
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Chandan-Kumar-GN/Todoapp.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f my-webapp/Dockerfile my-webapp/"
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                        sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
                    }
                }
            }
        }

        stage('Deploy to Server') {
            steps {
                script {
                    sshagent(['server-ssh']) {
                        sh """
                        ssh ec2-user@43.204.130.117 '
                        docker pull ${DOCKER_IMAGE}:${DOCKER_TAG} &&
                        docker stop webapp-container || true &&
                        docker rm webapp-container || true &&
                        docker run -d --name webapp-container -p 80:80 ${DOCKER_IMAGE}:${DOCKER_TAG}
                        '
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Deployment successful!"
        }
        failure {
            echo "Deployment failed!"
        }
    }
}
